name = "Murgle-Remastered"
authors = ["ClemenPine"]
board = "ortho"

[layers]
main = [
    "m l d f k  b p o u ' ;",
    "n r t h v  g y e i a /",
    "q j ( ) x  z w - , .  ",
    "s c                   ",
]